### ISSUE TITLE
AssertionError: Feature file for image 16395 does not exist.

### ISSUE THREAD

**Issue by NonlinearNimesh** [Nithin-Holla/meme_challenge#1]
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "train_uniter.py", line 181, in <module>
    config['test_loader'].append(test_data_loader(os.path.join(config['data_path'], test_file)))
  File "train_uniter.py", line 176, in test_data_loader
    confidence_threshold=config['object_conf_thresh'])
  File "/content/drive/My Drive/meme_challenge/data/dataset_template.py", line 66, in __init__
    self._prepare_data_list()
  File "/content/drive/My Drive/meme_challenge/data/meme_dataset.py", line 38, in _prepare_data_list
    self._load_dataset()
  File "/content/drive/My Drive/meme_challenge/data/meme_dataset.py", line 71, in _load_dataset
    assert os.path.isfile(feature_file_name), "Feature file for image {} does not exist.".format(img_id)
AssertionError: Feature file for image 16395 does not exist.

This is showing me the feature file does not exist for image 16395  but i have feature file with 16395.npy and 16395_info.npy in own_feature.

can you please help me out

**Comment by wangben718** [comment]
I have the same issue.

**Comment by liyouhua97** [comment]
I have met the same issue. Could you tell me how you solved it? My email: 15984767192@163.com. Thx a lot!

**Comment by liyouhua97** [comment]
I have met the same issue. Could you tell me how you solved it? My email: [15984767195@163.com]. Thx a lot!
